debug: false # debug log ???? logback ??? ???
management.endpoints.web.include: "*" # actuator? endpoint? ?? ??? ???? ??? ?? ? ? ??

logging:
  level:
    com.jake.projectboard: debug # ? ?????? ???? ?? ??? debug? ???
    org.springframework.web.servlet: debug # servlet??? ??? spring web? ?? ?? ???? ?? ??? ? ? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa ??? ????? ?????? ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: jake
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # spring boot 2.4 ?? ??, test? db data? ??
    hibernate.ddl-auto: create # entity? table data? ?? ddl? ???? ??
    # open-in-view: false
    show-sql: true # query ? ???
    properties: # ???? hibernate ORM hibernate properties - redhat property ??
      hibernate.format_sql: true # ? ?? ??? debug ???? format ??
      hibernate.default_batch_fetch_size: 100 # ??? ??? ???? ?? ? ?? ??? ???? ? N+1??? ?? ?? ??? 100? ??
#  h2.console.enabled: false # in memory ?? ?
  sql.init.mode: always #
  # thymeleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated

--- # ? 3? ???? ???? document? ?? ? ??

#spring:
#  config.activate.on-profile: testdb # testdb ???? ???? ? ??? ????
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none # test ??? ???? ??? -

---

